//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.SharedKernel.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERP.SharedKernel.Localization.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        internal static string auth_invalid_credentials {
            get {
                return ResourceManager.GetString("auth.invalid_credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page deleted successfully.
        /// </summary>
        internal static string page_deleted {
            get {
                return ResourceManager.GetString("page.deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page not found.
        /// </summary>
        internal static string page_notfound {
            get {
                return ResourceManager.GetString("page.notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages retrieved successfully.
        /// </summary>
        internal static string pages_retrieved {
            get {
                return ResourceManager.GetString("pages.retrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role {0} already Role {0} already exists.
        /// </summary>
        internal static string role_already_exists {
            get {
                return ResourceManager.GetString("role.already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role created successfully.
        /// </summary>
        internal static string role_created {
            get {
                return ResourceManager.GetString("role.created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role deleted successfully.
        /// </summary>
        internal static string role_deleted {
            get {
                return ResourceManager.GetString("role.deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete role because it has assigned users.
        /// </summary>
        internal static string role_has_users {
            get {
                return ResourceManager.GetString("role.has_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role not found.
        /// </summary>
        internal static string role_notfound {
            get {
                return ResourceManager.GetString("role.notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role updated successfully.
        /// </summary>
        internal static string role_updated {
            get {
                return ResourceManager.GetString("role.updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles retrieved successfully.
        /// </summary>
        internal static string roles_retrieved {
            get {
                return ResourceManager.GetString("roles.retrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created successfully.
        /// </summary>
        internal static string user_created {
            get {
                return ResourceManager.GetString("user.created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deleted successfully.
        /// </summary>
        internal static string user_deleted {
            get {
                return ResourceManager.GetString("user.deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email {0} is already in use.
        /// </summary>
        internal static string user_email_exists {
            get {
                return ResourceManager.GetString("user.email_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful.
        /// </summary>
        internal static string user_login_success {
            get {
                return ResourceManager.GetString("user.login_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        internal static string user_notfound {
            get {
                return ResourceManager.GetString("user.notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User updated successfully.
        /// </summary>
        internal static string user_updated {
            get {
                return ResourceManager.GetString("user.updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username {0} is already in use.
        /// </summary>
        internal static string user_userName_exists {
            get {
                return ResourceManager.GetString("user.userName_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users retrieved successfully.
        /// </summary>
        internal static string users_retrieved {
            get {
                return ResourceManager.GetString("users.retrieved", resourceCulture);
            }
        }
    }
}
